name: Build claude image

on:
  push:
    branches: [ main ]
    paths:
    - "claude/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t tbalthazar/claude-code-dev:latest claude
        
      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "tbalthazar" --password-stdin
        
      - name: Push image
        run: docker push tbalthazar/claude-code-dev:latest
